AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String
    Default: "" 

  ResourcePrefix:
    Type: String
    Default: ""  

  Tags:
    Type: String
    Default: ""

  Region:
    Type: String
    Default: "us-east-1"  

  Stage:
    Type: String
    Default: ""  

  ArtifactBucketName:
    Type: String
    Default: ""
    Description: Name of the S3 bucket for storing artifacts.

  codePileLineStackName:
    Type: String
    Default: ""
  PipelineName:
    Type: String
    Default: ""
    Description: Name of the CodePipeline.

  deployBuildName:
    Type: String
    Default: deployBuild
    Description: "The name of the deployment build."
  
  layerBuildName:
    Type: String
    Default: layerBuild
    Description: "The name of the layer build."
  
  unitTestBuildName:
    Type: String
    Default: unitTestBuild
    Description: "The name of the unit test build."

  codePileLineStackName:
    Type: String
    Default: ""
    Description: Name of the CloudFormation stack.

  GitHubOwner:
    Type: String
    Default: ""
    Description: GitHub username or organization.
  GitHubRepo:
    Type: String
    Default: ""
    Description: GitHub repository name.

  GitHubBranch:
    Type: String
    Default: ""
    Description: GitHub branch name

  GitHubConnectionName:
    Type: String
    Default: ""
    Description: "Name of the AWS CodeStar Connection"

  GitHubProviderType:
    Type: String
    Default: ""
    Description: "Provider type for CodeStar Connection (e.g., GitHub, Bitbucket, GitLab)"  
  
  DynamoDBTableName:
    Type: String
    Default: ""
    Description: "Name of the DynamoDB Table"

  CloudFormationS3Bucket:
    Type: String
    Default: ""
    Description: "S3 bucket for CloudFormation templates"

  TemplateFile:
    Type: String
    Default: ""
    Description: "Path to the CloudFormation template"

  LambdaFunctionName:
    Type: String
    Default: ""
    Description: "Name of the Lambda function"

  CloudFormationStackName:
    Type: String
    Default: ""
    Description: "Name of the CloudFormation stack"

Resources:
  GitHubCodeStarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: !Sub ${Environment}-${ResourcePrefix}-${GitHubConnectionName}
      ProviderType: !Ref GitHubProviderType

  ArtifactS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Environment}-${ResourcePrefix}-${ArtifactBucketName}

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [codepipeline.amazonaws.com]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket  
                  - s3:ListObjectsV2
                Resource: "*"
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: "*" 

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildS3FullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"

        - PolicyName: CodeBuildFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:*
                Resource: "*"

        - PolicyName: CloudFormationFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: "*"

        - PolicyName: IAMPassRoleForCodeBuild
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                  - iam:GetRole
                Resource: "*"

        - PolicyName: GitHubConnectionAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: "*"

        - PolicyName: AmazonAPIGatewayAdministrator
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:*
                Resource: "*"

        - PolicyName: AmazonDynamoDBFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"

        - PolicyName: IAMFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:*
                Resource: "*"

        - PolicyName: AWSLambdaFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:*
                Resource: "*"

        - PolicyName: CloudWatchLogsFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"

  UnitTestBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${Environment}-${ResourcePrefix}-${unitTestBuildName}
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-unittest.yml

  # 🔹 Layer Packaging CodeBuild Project
  LayerBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${Environment}-${ResourcePrefix}-${layerBuildName}
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: ENVIRONMENT
          Value: !Ref Environment
        - Name: REGION
          Value: !Ref Region 
        - Name: TEMPLATE_FILE
          Value: !Ref TemplateFile   
        - Name: S3_BUCKET
          Value: !Sub ${Environment}-${ResourcePrefix}-${CloudFormationS3Bucket}  
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-layer.yml

  DeployBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${Environment}-${ResourcePrefix}-${deployBuildName}
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: ENVIRONMENT
          Value: !Ref Environment
        - Name: DYNAMODB_TABLE_NAME
          Value: !Ref DynamoDBTableName
        - Name: S3_BUCKET
          Value: !Sub ${Environment}-${ResourcePrefix}-${CloudFormationS3Bucket}
        - Name: TEMPLATE_FILE
          Value: !Ref TemplateFile
        - Name: LAMBDA_FUNCTION_NAME
          Value: !Ref LambdaFunctionName
        - Name: STACK_NAME
          Value: !Sub ${Environment}-${ResourcePrefix}-${CloudFormationStackName} 
        - Name: REGION
          Value: !Ref Region  
        - Name: STAGE
          Value: !Ref Stage  
        - Name: TAGS
          Value: !Ref Tags  
      Source:
        Type: CODEPIPELINE
        BuildSpec: "buildspec-deploy.yml"
      TimeoutInMinutes: 10

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${Environment}-${ResourcePrefix}-${PipelineName}
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactS3Bucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: !Ref GitHubCodeStarConnection   # we acn also mention like this    ConnectionArn: !GetAtt GitHubCodeStarConnection.ConnectionArn  
                FullRepositoryId: !Sub "${GitHubOwner}/${GitHubRepo}" 
                BranchName: !Ref GitHubBranch
                OutputArtifactFormat: "CODE_ZIP"
              OutputArtifacts:
                - Name: SourceArtifact

        - Name: UnitTest
          Actions:
            - Name: UnitTestAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: UnittestArtifact
              Configuration:
                ProjectName: !Ref UnitTestBuildProject

        - Name: LayerPackaging
          Actions:
            - Name: CreateLayer
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: UnittestArtifact 
              OutputArtifacts:
                - Name: LayerArtifact
              Configuration:
                ProjectName: !Ref LayerBuildProject

        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: LayerArtifact 
              OutputArtifacts:
                - Name: DeployArtifact    
              Configuration:
                ProjectName: !Ref DeployBuildProject

